# Generated by Django 4.2.6 on 2023-12-07 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='user_permissions',
        ),
    ]
