# Generated by Django 4.2.6 on 2023-12-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='cart',
            field=models.ManyToManyField(blank=True, to='shops.cartitem'),
        ),
    ]
