# Generated by Django 4.2.6 on 2023-11-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appuser_is_active_appuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
