# Generated by Django 4.2.6 on 2023-12-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='username',
            field=models.CharField(default=1, max_length=55, unique=True),
            preserve_default=False,
        ),
    ]
