# Generated by Django 4.2.6 on 2023-12-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_appuser_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='cart',
        ),
    ]
