# Generated by Django 4.2.6 on 2023-12-04 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_cart_cartitem'),
        ('accounts', '0005_remove_appuser_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.cart'),
        ),
    ]
