# Generated by Django 4.2.6 on 2023-11-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='shop_images/')),
                ('type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=155)),
            ],
        ),
    ]
