# Generated by Django 4.2.6 on 2023-11-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='image',
        ),
        migrations.AddField(
            model_name='shop',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
