# Generated by Django 4.2.6 on 2023-11-25 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_shop_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shops.shop'),
        ),
    ]
