# Generated by Django 4.2.6 on 2023-11-29 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
